### ISSUE TITLE
Add feature to ignore URL patterns

### ISSUE THREAD

**Issue by slaterslater** [TDDR/checkThatLink#11]
* If `--ignore`, `-i` or `\i` flag present, program should take a filepath and use it to load and parse an ignored URLs text file. 
* If the ignore file isn't found, give an appropriate error message. 
* Otherwise, all URLs should be checked against this list to see if they need to be ignored.

**Comment by TDDR** [comment]
So I tested out your code  and there's one tiny issue. According to the requirements an invalid ignore file should give an error message and exit. 
```
Fourth, a file with anything other than a comment (#) or URL (http://, https://) is invalid:

# This is invalid.  It doesn't use http:// or https://
www.google.com

If the file isn't valid, give an appropriate error message and exit. Otherwise, use the file's URL patterns to test all the URLs being processed, skipping any that match.
```

Other then that it looks great!

**Comment by slaterslater** [comment]
I just pushed [246ca6b](https://github.com/slaterslater/checkThatLink/commit/246ca6b20ebf0e92c4e459e12b2da23154f09e07) to update `getIgnoreList()`
```python
with open(ignoreFile) as src:
  text = src.read() 
  found = re.findall('^https?://.*[^\s/]', text, flags=re.MULTILINE)
  comment = re.search('^#.*', text, flags=re.MULTILINE)
  return found if comment or found else sys.exit(1)
```
If `ignoreFile` is provided and both `found` and `comment` are empty, then it must be invalid

**Comment by TDDR** [comment]
Great, thanks for making those changes. I manually merged it and your branch is now part of my master branch!
